### ISSUE TITLE
Unsupported operation: Socket constructor using Flutter Web

### ISSUE THREAD

**Issue by Razzorback225** [robertodoering/dart_mpd#2]
Hi, 

While trying to use your package in a Web Flutter app, each time I try to connect to my MPD device this error appears.
After some searches on google it seems to indicate that the package is not intended to be used in a flutter web app.

Are you aware of this? Because your Readme file says that this is working on web too.

Regards

**Comment by robertodoering** [comment]
Hey, you are right - it doesn't support web.
MPD doesn't allow connection through a web socket, so supporting web is not possible (yet). https://github.com/MusicPlayerDaemon/MPD/issues/1511

Sorry for the misleading info in the readme, I've updated it.
