### ISSUE TITLE
Error on command arguments with spaces

### ISSUE THREAD

**Issue by dangodai** [robertodoering/dart_mpd#3]
Hi, thanks for the library.

I was trying out the `readpicture` and `albumart` commands and was getting the following errors.

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MpdResponse.error(message: [2@0] {albumart} wrong number of arguments for "albumart")
#0      MpdClient._send (package:dart_mpd/src/client.dart:1304:29)
```

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MpdResponse.error(message: [2@0] {readpicture} wrong number of arguments for "readpicture")
#0      MpdClient._send (package:dart_mpd/src/client.dart:1304:29)
```

Upon further investigation I realized this is because my URIs contained spaces and the MPD docs state: ["If arguments contain spaces, they should be surrounded by double quotation marks."](https://mpd.readthedocs.io/en/latest/protocol.html#requests)

Sure enough, manually quoting my argument fixes the issue

```dart
await client.readpicture('"${currentSong.file}"', 0);
```

This will be a common issue with any command that takes a URI, and possibly other arguments I haven't looked at where spaces will be common. Example, passing the same URI argument to `add` creates a similar error:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MpdResponse.error(message: [2@0] {add} too many arguments for "add")
#0      MpdClient._send (package:dart_mpd/src/client.dart:1304:29)
```

Manually quoting the argument works, but I would suggest that the library doing it would be more expected behaviour. If you decide to maintain the current behaviour, a note in the code and readme docs would be helpful.

Side question: Is that goal of this library to simply mirror the mpd protocol? Would you consider helper functions such as looping to grab an entire image, instead of a single chunk?

Thanks

**Comment by robertodoering** [comment]
You're right, it's reasonable for the library to be smart enough to wrap the arguments with quotation marks when necessary, thanks for the suggestion!

> Side question: Is that goal of this library to simply mirror the mpd protocol? Would you consider helper functions such as looping to grab an entire image, instead of a single chunk?

I want the library to just mirror the protocol and handle the communication to keep it as minimal as I can.
